### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel zkfinger)

### ISSUE THREAD

**Issue by Sirjiskit** [Mamasodikov/zk_finger_10#3]
I cloned the repo. run the xample but I got below can you tell me what the cause?
The Flutter DevTools debugger and profiler on TPS360 is available at:
http://127.0.0.1:9104?uri=http://127.0.0.1:56705/9F2_EWmC25I=/       
E/flutter ( 9172): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel zkfinger)
E/flutter ( 9172): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter ( 9172): <asynchronous suspension>
E/flutter ( 9172): #1      _MyAppState.initPlatformState (package:zkfinger10_example/main.dart:66:25)
E/flutter ( 9172): <asynchronous suspension>

**Comment by Mamasodikov** [comment]
Hi, thanks for opening an issue, can you run "flutter doctor" and tell us what it prints

**Comment by Sirjiskit** [comment]
PS C:\dev\new\zk_finger_10\example> flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3880], locale en-NG)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.7.5)
[!] Android Studio (version 2022.3)
    X Unable to find bundled Java version.
[!] Android Studio (version 2023.3)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.0)
[√] Connected device (4 available)
[√] Network resources                                

! Doctor found issues in 2 categories.

**Comment by israUSA** [comment]
Hey bro, I was able to run the sample, but I have the same error when integrating it into my own project. Were you able to resolve it? Let's see if your solution can help me in any way.

`════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel com.mamasodikov.zkfinger10/finger_image:
MissingPluginException(No implementation found for method listen on channel com.mamasodikov.zkfinger10/finger_image)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
platform_channel.dart:332
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676:9)
platform_channel.dart:676
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
MissingPluginException(No implementation found for method listen on channel com.mamasodikov.zkfinger10/status_change)`

**Comment by Mamasodikov** [comment]
Hi, thanks for opening an issue,
Have you stopped app and re run after adding plugin to your project?

**Comment by Nik8110** [comment]
i got same issue

**Comment by israUSA** [comment]
t

> ¡Tengo el mismo problema! Reinicié la aplicación 2 o 3 veces, pero sigue igual. ¿Puedes ayudarme?@Mamasodikov¿Debería ser necesario conectar el dispositivo de huellas dactilares?
> 
> no se está inicializando E/flutter (9601): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Excepción no controlada: MissingPluginException(No se encontró implementación para el método getPlatformVersion en el canal zkfinger) E/flutter (9601) : #0 MethodChannel._invokeMethod (paquete:flutter/src/services/platform_channel.dart:332:7) E/flutter (9601): E/flutter (9601): #1 _MyAppState.initPlatformState (paquete:zkfinger10_example/main.dart :66:25) E/aleteo (9601): E/aleteo (9601):

I was able to fix it, downgrade Flutter to version 3.19.0 with fvm and in the app build.gradle configure minSDK = 21 and targetSdk = 31.

**Comment by Nik8110** [comment]
Thanks Bro! @israUSA Working fine now.

**Comment by Rogerr14** [comment]
Hi, i change the grale version in gradle-wrapper.propierties to7.5 and change the flutter version to 3.19.0, I don't think any other changes were necessary, but in any case, I'm going to detail the changes I made correctly.

**Comment by Mamasodikov** [comment]
Plugin is upgraded, I'll close the issue for now, open if you still encounter
